### ISSUE TITLE
It seems the mean teacher does not contribute to the loss.

### ISSUE THREAD

**Issue by jonkoi** [YU1ut/MixMatch-pytorch#13]
The teacher model ema_model is updated every step, but it is never use for forward prop. Thus, I am not sure if mean teacher does anything.

**Comment by SanyouWu** [comment]
The ema_model only used in valuation and test step. Actually, I think it does not work to improve the model's efficiency. @jonkoi

**Comment by jonkoi** [comment]
I see. Thanks for clearing this up for me. Closing this issue.
