### ISSUE TITLE
Is my data wrong?

### ISSUE THREAD

**Issue by sailor88128** [YU1ut/MixMatch-pytorch#2]
When I run the code directly, it seems no targets in this CIFAR10?

```
Files already downloaded and verified
Traceback (most recent call last):
  File "train.py", line 431, in <module>
    main()
  File "train.py", line 88, in main
    train_labeled_set, train_unlabeled_set, val_set, test_set = dataset.get_cifar10('./data', args.n_labeled, transform_train=transform_train, transform_val=transform_val)
  File "/usr/workspace/2-DCASE/dcase2019/MixMatch-pytorch/dataset/cifar10.py", line 21, in get_cifar10
    train_labeled_idxs, train_unlabeled_idxs, val_idxs = train_val_split(base_dataset.targets, int(n_labeled/10))
AttributeError: 'CIFAR10' object has no attribute 'targets'

```

**Comment by liminxian** [comment]
Hi, yu. I also met this issue. According the document of pytorch, CIFAR10 doesn't have such an attribute 'targets'. So how did you get the targets of images here? Thanks!

**Comment by YU1ut** [comment]
Hi! Updating torchvision to 0.2.2 or 0.3.0 can solve this problem. They rename the variables of cifar10 in the new versions. Maybe I should highlight this in the readme.

**Comment by liminxian** [comment]
Many Thanks! It works for me. Great work.
