### ISSUE TITLE
About the settings of parameters and CIFAR100

### ISSUE THREAD

**Issue by wjwstc123** [YU1ut/MixMatch-pytorch#3]
I use this code to train CIFAR100 dataSet of 20 class, but the final top1 socre is 0.68. Can you tell me the settings of some parameters or other probable questions? For example the value of final **LR**.

**Comment by ClayZhang0403** [comment]
> I use this code to train CIFAR100 dataSet of 20 class, but the final top1 socre is 0.68. Can you tell me the settings of some parameters or other probable questions? For example the value of final **LR**.

well, I use this code to train CIFAR100 dataSet of 20 class, i tune the parameters ,and the result is 0.88

**Comment by wjwstc123** [comment]
Can you give me your social account? Like WeChat.------------------ 原始邮件 ------------------
发件人: "ClayZhang0403"<notifications@github.com>
发送时间: 2019年6月1日(星期六) 中午12:58
收件人: "YU1ut/MixMatch-pytorch"<MixMatch-pytorch@noreply.github.com>;
抄送: "wjwstc123"<269182663@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [YU1ut/MixMatch-pytorch] About the settings of parameters andCIFAR100 (#3)


 
I use this code to train CIFAR100 dataSet of 20 class, but the final top1 socre is 0.68. Can you tell me the settings of some parameters or other probable questions? For example the value of final LR.
  
well, I use this code to train CIFAR100 dataSet of 20 class, i tune the parameters ,and the result is 0.88
 
&mdash;

**Comment by ClayZhang0403** [comment]
> Can you give me your social account? Like WeChat.------------------ 原始邮件 ------------------ 发件人: "ClayZhang0403"<notifications@github.com> 发送时间: 2019年6月1日(星期六) 中午12:58 收件人: "YU1ut/MixMatch-pytorch"<MixMatch-pytorch@noreply.github.com>; 抄送: "wjwstc123"<269182663@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [YU1ut/MixMatch-pytorch] About the settings of parameters andCIFAR100 (#3) I use this code to train CIFAR100 dataSet of 20 class, but the final top1 socre is 0.68. Can you tell me the settings of some parameters or other probable questions? For example the value of final LR. well, I use this code to train CIFAR100 dataSet of 20 class, i tune the parameters ,and the result is 0.88 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

sorry, I seldom use wechat,  I'm master in Berkeley. so you can contact with Skype ,my account is clayzhang0403@outlook.com, also, u can send ur code to email  ,may be i will check it after class

**Comment by wjwstc123** [comment]
Aha, i already known the reason why my code can not work. Thanks for your help.
