### ISSUE TITLE
The description of the parameter is not clear

### ISSUE THREAD

**Issue by ustcjerry** [YU1ut/MixMatch-pytorch#32]
https://github.com/YU1ut/MixMatch-pytorch/blob/a738cc95aae88f76761aeeb405201bc7ae200e7d/train.py#L44-L47

They are both "Number of labeled data", and i think maybe change `val_iteration` to `train_iteration` makes it better?

**Comment by YU1ut** [comment]
fixed by cf731bcae2e2caaf946c2071d8bb4b8fdd2b9fd0
