### ISSUE TITLE
A question on lambda_u

### ISSUE THREAD

**Issue by zhaozhengChen** [YU1ut/MixMatch-pytorch#33]
Hi,

In the official implementation, the authors ramp up labmda_u in 16 epochs, but in your implementation, lambada_u is gradually increased in the whole training process(1024 epochs).

**Comment by YU1ut** [comment]
You can change this line to do that.
https://github.com/YU1ut/MixMatch-pytorch/blob/master/train.py#L360

But gradually increasing lambada_u in the whole training process seems to lead to better results according to https://github.com/YU1ut/MixMatch-pytorch/issues/9.

**Comment by zhaozhengChen** [comment]
Thanks.
